### ISSUE TITLE
'System.Runtime' which was not found in the GAC.

### ISSUE THREAD

**Issue by pizycki** [dennisroche/xunit.ioc.autofac#5]
```
Severity Code Description Project File Line Suppression State
Error Failed to add reference. The package 'xunit2.ioc.autofac' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
```

Repro steps:
1. create new library project (.NET 4.6)
2. install xunit @ 2.2 beta build 3300
3. install `xunit2.ioc.autofac`

**Comment by dennisroche** [comment]
@pizycki could you attach the new library project so that I can debug further? 

Initial step to figure this out will be to download the lib and include the as a local project reference.

**Comment by pizycki** [comment]
There you go
[IzzyDev.Integro.zip](https://github.com/dennisroche/xunit.ioc.autofac/files/513125/IzzyDev.Integro.zip)

**Comment by RavindraBarapatre** [comment]
I am also getting same error.

**Comment by dennisroche** [comment]
I'm seeing a different error when trying to install the lib package. 

```
Unable to find a version of 'Autofac' that is compatible with 'xunit2.ioc.autofac 1.0.2 constraint: Autofac (>= 4.1.1)'.
```

I'll continue to investigate.

**Comment by pizycki** [comment]
Well, I haven't installed Autofac on this project.
I did it now, but nothing have changed, the problem persists.

**Comment by gitfool** [comment]
I'm hitting this as well. Any chance the proposed fix can be merged soon?

**Comment by dennisroche** [comment]
Apologies. I didn't know there was a PR up. I'll review it now.

**Comment by dennisroche** [comment]
@gitfool fix is merged and nuget package is deployed. thanks @pizycki. glad that i setup a build/deploy early on.

**Comment by gitfool** [comment]
Gotta love Cake. Cheers! 🍰

**Comment by gitfool** [comment]
@dennisroche Except that didn't make any difference. Still getting the error trying to install 1.0.3!?

**Comment by dennisroche** [comment]
@gitfool bugger. i took the fix assuming that it worked for @pizycki.

**Comment by gitfool** [comment]
Yeah I assumed the same. The link in the PR implied it was enough. Are you able to repro with a new project targeting .NET FW 4.6.1 using the latest Autofac and xUnit prerelease?

**Comment by dennisroche** [comment]
I think I see the error with that PR - the `System.Runtime` needs to be added a `dependency`. I thought it was odd when I merged, however didn't have time to verify.

**Comment by pizycki** [comment]
Weird, it worked for me. Yet, I'm .net core newbie, so I could did something wrong.
Waiting for PR from @dennisroche to be accepted.

PS: 🍰 is great !

**Comment by dennisroche** [comment]
:cake: all things. 👍 

I merge the PR and deploy the `1.0.4` package. Usually would want to use pre-release tag however don't think many people are using this lib at the moment.

**Comment by dennisroche** [comment]
@pizycki the `System.Runtime` piece you added in needed to be listed as a dependency, outside that it would have been ignored. I think. Let's try. PR is merged.

**Comment by gitfool** [comment]
I don't see 1.0.4. Should it be available now?

**Comment by dennisroche** [comment]
I forgot to tag the build to generate the correct release number. It should be available now...

**Comment by gitfool** [comment]
I can install the package! 😉

**Comment by dennisroche** [comment]
:+1: great :)
